version: "3"
services:
  api_hulk_store:
    container_name: api_fastify_hulk_store
    restart: always
    build: api_hulk/.
    volumes:
      - ./api_hulk:/usr/src/app
      - ./api_hulk/node_modules:/usr/src/app/node_modules

    depends_on:
      - mongo
    environment:
      - HULKSTORE_DOMAIN=${HULKSTORE_DOMAIN}
    ports:
      - "3001:3001"
    links:
      - mongo

  mongo:
    container_name: mongo_hulk_store
    image: mongo:4
    volumes:
      - mongo_hulk_store_volumen:/data/db
    ports:
      - "27017:27017"
    logging:
      driver: none
    labels:
      traefik.port: 27017

  web_hulk_store:
    container_name: web_hulk_store
    restart: always
    build:
      context: ./web_hulk
      dockerfile: Dockerfile.developer
    ports:
      - 4201:4201
    volumes:
      - ./web_hulk:/usr/src/app
      - ./web_hulk/node_modules:/usr/src/app/node_modules
    depends_on:
      - api_hulk_store

volumes:
  mongo_hulk_store_volumen:

